#docker-compose up --build (--build command is for rebuilding images/latest changes)
#for a single container
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
---------------------------------------------------------
#another docker compose
version: '3'
services: 
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports: 
      - "8081:8081"
      
